services:
  # Main Server
  nginx:
    container_name: nginx
    image: docker.io/nginx:1.25.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress-f.kth.se
      - wordpress-fysikalen.se
      - wordpress-ffusion.se
      - wordpress-fadderiet
      - sangbok
      - kons-count
      - cyberfohs
      - bittan_test_server
      - bittan-marke-server
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf

      - ./services/certbot/conf/live:/etc/nginx/certificates/live
      - ./services/certbot/conf/archive:/etc/nginx/certificates/archive

      - ./services/certbot/static/:/certbot

      - ./services/f.kth.se/wordpress:/f.kth.se/wordpress
      - ./services/fysikalen.se/wordpress:/fysikalen.se/wordpress
      - ./services/ffusion.se/wordpress:/ffusion.se/wordpress
      - ./services/fadderiet/wordpress:/f.kth.se/fadderiet

      - ./services/kons-count/static:/f.kth.se/counter
      - ./services/namndkompassen:/f.kth.se/namndkompassen
      - ./services/signature:/f.kth.se/signature

      - ./services/arcade:/f.kth.se/arcade
      - ./services/arcade/home/index.html:/f.kth.se/arcade/index.html

      - ./services/cyberfohs/static:/f.kth.se/cyberfohs/public/staticfiles
      - ./services/cyberfohs/media:/f.kth.se/cyberfohs/public/media

      - ./services/misc/GoogleIDPMetadata.xml:/f.kth.se/google/GoogleIDPMetadata.xml
      - ./services/misc/googlebbfc4851489dd255.html:/f.kth.se/googlebbfc4851489dd255.html
      - ./services/misc/f.png:/f.kth.se/f.png
      - ./services/misc/logo.png:/f.kth.se/logo.png
      - ./services/misc/robots.txt:/f.kth.se/robots.txt

      - ./services/bittan_test/static:/f.kth.se/bittan-test/static
      - ./services/bittan_test_frontend:/f.kth.se/biljett-test

      - ./services/bittan_marke/static:/f.kth.se/bittan-marke-django/static
      - ./services/bittan_marke_frontend:/f.kth.se/bittan-marke

  # Provides SSL certificates
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./services/certbot/static/:/var/www/certbot/
      - ./services/certbot/conf/:/etc/letsencrypt/

  # f.kth.se Wordpress and Database
  mariadb-f.kth.se:
    container_name: mariadb-f.kth.se
    image: docker.io/mariadb
    restart: unless-stopped
    volumes:
      - ./services/f.kth.se/mariadb:/var/lib/mysql
    env_file: ./services/f.kth.se/.env
    environment:
      MARIADB_DATABASE: fkthse

  wordpress-f.kth.se:
    container_name: wordpress-f.kth.se
    image: docker.io/wordpress:6.4.3-php8.1-fpm-alpine
    restart: unless-stopped
    volumes:
      - ./services/f.kth.se/wordpress:/var/www/html/
    depends_on:
      - mariadb-f.kth.se
    env_file: ./services/f.kth.se/.env
    environment:
      WORDPRESS_DB_HOST: mariadb-f.kth.se
      WORDPRESS_DB_NAME: fkthse
      WORDPRESS_TABLE_PREFIX: wp_

  # fysikalen.se Wordpress and Database
  mariadb-fysikalen.se:
    container_name: mariadb-fysikalen.se
    image: docker.io/mariadb
    restart: unless-stopped
    volumes:
      - ./services/fysikalen.se/mariadb/:/var/lib/mysql
    env_file: ./services/fysikalen.se/.env
    environment:
      MARIADB_DATABASE: fysikalense

  wordpress-fysikalen.se:
    container_name: wordpress-fysikalen.se
    image: docker.io/wordpress:6.4.3-php8.1-fpm-alpine
    restart: unless-stopped
    volumes:
      - ./services/fysikalen.se/wordpress:/var/www/html/
    depends_on:
      - mariadb-fysikalen.se
    env_file: ./services/fysikalen.se/.env
    environment:
      WORDPRESS_DB_HOST: mariadb-fysikalen.se
      WORDPRESS_DB_NAME: fysikalense
      WORDPRESS_TABLE_PREFIX: wp_


  # ffusion.se Wordpress and Database
  mariadb-ffusion.se:
    container_name: mariadb-ffusion.se
    image: docker.io/mariadb
    restart: unless-stopped
    volumes:
      - ./services/ffusion.se/mariadb:/var/lib/mysql
    env_file: ./services/ffusion.se/.env
    environment:
      MARIADB_DATABASE: ffusionse


  wordpress-ffusion.se:
    container_name: wordpress-ffusion.se
    image: docker.io/wordpress:6.4.3-php8.1-fpm-alpine
    restart: unless-stopped
    volumes:
      - ./services/ffusion.se/wordpress:/var/www/html/
    depends_on:
      - mariadb-ffusion.se
    env_file: ./services/ffusion.se/.env
    environment:
      WORDPRESS_DB_HOST: mariadb-ffusion.se
      WORDPRESS_DB_NAME: ffusionse
      WORDPRESS_TABLE_PREFIX: wp_


  # f.kth.se/fadderiet Wordpress and Database
  mariadb-fadderiet:
    container_name: mariadb-fadderiet
    image: docker.io/mariadb
    restart: unless-stopped
    volumes:
      - ./services/fadderiet/mariadb:/var/lib/mysql
    env_file: ./services/fadderiet/.env
    environment:
      MARIADB_DATABASE: fadderiet


  wordpress-fadderiet:
    container_name: wordpress-fadderiet
    image: docker.io/wordpress:6.4.3-php8.1-fpm-alpine
    restart: unless-stopped
    volumes:
      - ./services/fadderiet/wordpress:/var/www/html/
    depends_on:
      - mariadb-fadderiet
    env_file: ./services/fadderiet/.env
    environment:
      WORDPRESS_DB_HOST: mariadb-fadderiet
      WORDPRESS_DB_NAME: fadderiet
      WORDPRESS_TABLE_PREFIX: wp_

  # Other apps for f.kth.se

  ## Sangbok
  sangbok:
    container_name: sangbok
    image: ghcr.io/fysiksektionen/sangbok-html@sha256:${SANGBOK_SHA}


  ## Kons Count
  kons-count-redis:
    container_name: kons-count-redis
    image: docker.io/redis:alpine
    volumes:
      - ./services/kons-count/redis/:/data

  kons-count:
    container_name: kons-count
    image: ghcr.io/fysiksektionen/kons_count:${KONS_COUNT_VERSION}
    volumes:
      - ./services/kons-count/server/service_account_auth_file.json:/server/service_account_auth_file.json
      - ./services/kons-count/server/.env:/server/.env
    depends_on:
      - kons-count-redis
    init: true

  cyberfohs:
    container_name: cyberfohs
    image: ghcr.io/fysiksektionen/cyberfohs-appen:${CYBERFOHS_VERSION}
    volumes:
      - ./services/cyberfohs/static:/src/static
      - ./services/cyberfohs/media:/src/media
      - ./services/cyberfohs/data/db:/src/db
      - ./services/cyberfohs/secretkey.txt:/src/secretkey.txt

    init: true

  ## bittan_test
  bittan_test_server:
    container_name: bittan_test_server
    image: ghcr.io/fysiksektionen/bittan-backend:${BITTAN_TEST_VERSION}
    env_file: ./services/bittan_test/bittan_test_server.env
    volumes:
      - ./services/bittan_test/static:/bittan/static
      - ./services/bittan_test/swish_certificates:/bittan/certificates
      - ./services/bittan_test/gmail_creds:/bittan/gmail_creds
    environment:
      BITTAN_BACKEND_URL: "https://f.kth.se/bittan-test"
      ALLOWED_HOSTS: '["f.kth.se"]'
      DATABASE_HOST: bittan_test_postgres
      DATABASE_NAME: bittan_test_db
      DATABASE_USER: postgres
      DATABASE_PORT: 5432
      SWISH_PEM_FILE_PATH: ./certificates/myCertificate.pem
      SWISH_KEY_FILE_PATH: ./certificates/PrivateKey.key
      SWISH_PAYEE_ALIAS: 1230810689
      SWISH_API_URL: https://staging.getswish.pub.tds.tieto.com/swish-cpcapi
      DEBUG: "False"
    depends_on:
      bittan_test_postgres:
        condition: service_healthy

  bittan_test_postgres:
    container_name: bittan_test_postgres
    image: postgres
    volumes:
      - ./services/bittan_test/postgres_data:/var/lib/postgresql/data
    env_file: ./services/bittan_test/bittan_test_postgres.env
    environment:
      POSTGRES_DB: bittan_test_db
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  ## bittan_marke
  bittan-marke-server:
    container_name: bittan-marke-server
    image: ghcr.io/fysiksektionen/bittan-backend:${BITTAN_MARKE_VERSION}
    env_file: ./services/bittan_marke/bittan_marke_server.env
    volumes:
      - ./services/bittan_marke/static:/bittan/static
      - ./services/bittan_marke/swish_certificates:/bittan/certificates
      - ./services/bittan_marke/gmail_creds:/bittan/gmail_creds
      - ./services/bittan_marke/logs:/bittan/logs
    environment:
      BITTAN_BACKEND_URL: "https://f.kth.se/bittan-marke-django"
      BITTAN_FRONTEND_URL: "https://f.kth.se/bittan-marke"
      ALLOWED_HOSTS: '["f.kth.se", "bittan-marke-server"]'
      DATABASE_HOST: bittan_marke_postgres
      DATABASE_NAME: bittan_marke_db
      DATABASE_USER: postgres
      DATABASE_PORT: 5432
      SWISH_PEM_FILE_PATH: ./certificates/swish_certificate_202503132004.pem
      SWISH_KEY_FILE_PATH: ./certificates/MySwishKey.key
      SWISH_API_URL: https://cpc.getswish.net/swish-cpcapi
      DEBUG: "False"
    depends_on:
      bittan_marke_postgres:
        condition: service_healthy

  bittan_marke_postgres:
    container_name: bittan_marke_postgres
    image: postgres
    volumes:
      - ./services/bittan_marke/postgres_data:/var/lib/postgresql/data
    env_file: ./services/bittan_marke/bittan_marke_postgres.env
    environment:
      POSTGRES_DB: bittan_marke_db
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
