services:
  # Main Server
  nginx:
    container_name: nginx
    image: nginx:1.25.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress-f.kth.se
      - wordpress-fysikalen.se
      - wordpress-ffusion.se
      - sangbok
      - kons-count
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/certificates:/etc/nginx/certificates

      - ./services/f.kth.se/wordpress:/f.kth.se/wordpress
      - ./services/fysikalen.se/wordpress:/fysikalen.se/wordpress
      - ./services/ffusion.se/wordpress:/ffusion.se/wordpress

      - ./services/kons-count/static:/f.kth.se/counter
      - ./services/namndkompassen:/f.kth.se/namndkompassen

      - ./services/arcade:/f.kth.se/arcade
      - ./services/arcade/home/index.html:/f.kth.se/arcade/index.html

      - ./services/google/GoogleIDPMetadata.xml:/f.kth.se/google/GoogleIDPMetadata.xml

  # f.kth.se Wordpress and Database
  mariadb-f.kth.se:
    container_name: mariadb-f.kth.se
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./services/f.kth.se/mariadb:/var/lib/mysql
    env_file: ./services/f.kth.se/.env
    environment:
      MARIADB_DATABASE: db_name

  wordpress-f.kth.se:
    container_name: wordpress-f.kth.se
    # image: wordpress:6.4.3-php8.1-fpm-alpine
    image: wordpress:5.6.1-php8.0-fpm-alpine
    restart: unless-stopped
    volumes:
      - ./services/f.kth.se/wordpress:/var/www/html/
    depends_on:
      - mariadb-f.kth.se
    env_file: ./services/f.kth.se/.env
    environment:
      WORDPRESS_DB_HOST: mariadb-f.kth.se
      WORDPRESS_DB_NAME: db_name
      WORDPRESS_TABLE_PREFIX: wp_


  # fysikalen.se Wordpress and Database
  mariadb-fysikalen.se:
    container_name: mariadb-fysikalen.se
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./services/fysikalen.se/mariadb/:/var/lib/mysql
    env_file: ./services/fysikalen.se/.env
    environment:
      MARIADB_DATABASE: db_name

  wordpress-fysikalen.se:
    container_name: wordpress-fysikalen.se
    # image: wordpress:6.4.3-php8.1-fpm-alpine
    image: wordpress:5.6.1-php8.0-fpm-alpine
    restart: unless-stopped
    volumes:
      - ./services/fysikalen.se/wordpress:/var/www/html/
    depends_on:
      - mariadb-fysikalen.se
    env_file: ./services/fysikalen.se/.env
    environment:
      WORDPRESS_DB_HOST: mariadb-fysikalen.se
      WORDPRESS_DB_NAME: db_name
      WORDPRESS_TABLE_PREFIX: wp_


  # ffusion.se Wordpress and Database
  mariadb-ffusion.se:
    container_name: mariadb-ffusion.se
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./services/ffusion.se/mariadb:/var/lib/mysql
    env_file: ./services/ffusion.se/.env
    environment:
      MARIADB_DATABASE: db_name


  wordpress-ffusion.se:
    container_name: wordpress-ffusion.se
    image: wordpress:6.4.3-php8.1-fpm-alpine
    restart: unless-stopped
    volumes:
      - ./services/ffusion.se/wordpress:/var/www/html/
    depends_on:
      - mariadb-ffusion.se
    env_file: ./services/ffusion.se/.env
    environment:
      WORDPRESS_DB_HOST: mariadb-ffusion.se
      WORDPRESS_DB_NAME: db_name
      WORDPRESS_TABLE_PREFIX: wp_

  # Other apps for f.kth.se

  ## Sangbok
  sangbok:
    container_name: sangbok
    image: "ghcr.io/fysiksektionen/sangbok-html:latest"


  ## Kons Count
  kons-count-redis:
    container_name: kons-count-redis
    image: "redis:alpine"
    volumes:
      - ./services/kons-count/redis/:/data

  kons-count:
    container_name: kons-count
    image: ghcr.io/fysiksektionen/kons_count:${KONS_COUNT_VERSION}
    volumes:
      - ./services/kons-count/server/service_account_auth_file.json:/server/service_account_auth_file.json
      - ./services/kons-count/server/.env:/server/.env
    depends_on:
      - kons-count-redis
    init: true
