KONS_COUNT_VERSION=.env
ARCADE_VERSION=.env
ARCADE_HOME_VERSION=.env
NAMNDKOMPASSEN_VERSION=.env
SANGBOK_SHA=.env
CYBERFOHS_VERSION=./project-ops/cyberfohs/.env
SIGNATURE_VERSION=.env
BITTAN_MARKE_VERSION=./project-ops/bittan-marke/.env
BITTAN_FYSIKALEN_VERSION=./project-ops/bittan-fysikalen/.env
FNKTHSE_VERSION=./project-ops/fnkth.se/.env
VALKOMPASSEN_VERSION=./project-ops/valkompassen/.env
FNCRM_VERSION=./project-ops/fn-crm/.env

SERVER_URL=./project-ops/fn-crm/.env
STORAGE_TYPE=./project-ops/fn-crm/.env
IS_CONFIG_VARIABLES_IN_DB_ENABLED=./project-ops/fn-crm/.env
APP_SECRET=./project-ops/fn-crm/.env
PG_DATABASE_PASSWORD=./project-ops/fn-crm/.env
